import iron from './iron man.jpg';
import mug1 from './mug1.jpg';

export const tank=[{
    id:1,
    src:iron,
    description:'doll',
    name:'DOLL',
    price:200,
  },{
    id:2,
    src:iron,
    description:'doll',
    name:'DOLL',
    price:400,
  },{
    id:3,
    src:iron,
    description:'MUG',
    name:'MUG',
    price:1200,
  },{
    id:8,
    src:iron,
    description:'TOY',
    name:'TOY',
    price:2200,
  },{
    id:4,
    src:iron,
    description:'TOY',
    name:'TOY',
    price:200,
  },{
    id:5,
    src:iron,
    description:'MUG',
    name:'MUG',
    price:200,
  },{
    id:6,
    src:iron,
    description:'doll',
    name:'DOll',
    price:200,
  },{
    id:7,
    src:iron,
    description:'doll',
    name:'DOll',
    price:200,
  }]